# Load from environment variables or .env file
import os
from dotenv import load_dotenv

load_dotenv()

ASSEMBLY_AI_KEY = os.getenv("ASSEMBLY_AI_KEY")
GDRIVE_API_KEY = os.getenv("GDRIVE_API_KEY")
OPENAI_API_KEY = os.getenv("OPENAI_API_KEY")
OPENAI_ORG = os.getenv("OPENAI_ORG")
CLAUDE_API_KEY = os.getenv("CLAUDE_API_KEY")
GEMINI_API_KEY = os.getenv("GEMINI_API_KEY")
LINKEDIN_PASSWORD = os.getenv("LINKEDIN_PASSWORD")
HUGGING_FACE = os.getenv("HUGGING_FACE")
CODA_API_KEY = os.getenv("CODA_API_KEY")
LINKEDIN_EMAIL = os.getenv("LINKEDIN_EMAIL")
LINKEDIN_PASSWORD = os.getenv("LINKEDIN_PASSWORD")
LINKEDIN_LI_AT = os.getenv("LINKEDIN_LI_AT")
LINKEDIN_JSESSIONID = os.getenv("LINKEDIN_JSESSIONID")
HTML_TO_MARKDOWN_API_KEY = os.getenv("HTML_TO_MARKDOWN_API_KEY")
DEEPSEEK_API_KEY = os.getenv("DEEPSEEK_API_KEY")
PERPLEXITY_API_KEY = os.getenv("PERPLEXITY_API_KEY")
DISCORD_BOT_TOKEN = os.getenv("DISCORD_BOT_TOKEN")